if UnitClass("player") ~= "Druid" then return end

SLASH_IBLASTDRUID1 = "/iblast"
function SlashCmdList.IBLASTDRUID()
	IWin:InitializeRotation()
	IWin:TargetEnemy()
	IWin:UseItemTrinketOffensivePrepull(true)
	IWin:StartAttack()
	IWin:MarkOfTheWild()
	IWin:Thorns()
	IWin:CancelRoot()
	IWin:MoonkinForm()
	IWin:UseItemConsumableOffensiveNoGCDRanged()
	IWin:UseItemTrinketOffensiveNoGCDRanged()
	IWin:UseItemConsumableAOEOffensiveNoGCD()
	IWin:UseItemConsumableAOEOffensiveGCD()
	IWin:WrathOOC()
	IWin:StarfireOOC()
	IWin:InsectSwarm()
	IWin:Moonfire()
	IWin:Wrath()
	IWin:Starfire()
	IWin:InsectSwarmMoving()
	IWin:MoonfireMoving()
end

SLASH_IRUETOODRUID1 = "/iruetoo"
function SlashCmdList.IRUETOODRUID()
	IWin:InitializeRotation()
	IWin:TargetEnemy()
	IWin:UseItemTrinketOffensivePrepull(true)
	IWin:MarkOfTheWild()
	IWin:Thorns()
	IWin:BerserkFear()
	IWin:CancelRoot()
	IWin:CancelSnare()
	IWin:CatForm()
	IWin:TigersFury()
	IWin:SetReservedEnergyTigersFury()
	IWin:Pounce()
	IWin:Ravage()
	IWin:FaerieFireFeral()
	IWin:UseItemConsumableOffensiveNoGCD()
	IWin:UseItemTrinketOffensiveNoGCD()
	IWin:CastCDShortOffensiveNoGCD()
	IWin:CastCDShortOffensiveGCD()
	IWin:UseItemConsumableAOEOffensiveNoGCD()
	IWin:UseItemConsumableAOEOffensiveGCD()
	IWin:Rip()
	IWin:SetReservedEnergyRip()
	IWin:FerociousBite()
	IWin:SetReservedEnergyFerocious()
	IWin:Rake()
	IWin:SetReservedEnergyRake()
	IWin:Shred()
	IWin:SetReservedEnergyShred()
	IWin:Claw()
	IWin:FaerieFireFeralRefresh()
	IWin:Powershift()
	IWin:StartAttack()
end

SLASH_ITANKDRUID1 = "/itank"
function SlashCmdList.ITANKDRUID()
	IWin:InitializeRotation()
	IWin:CancelSalvation()
	IWin:TargetEnemy()
	IWin:MarkSkull()
	IWin:UseItemTrinketOffensivePrepull(true)
	IWin:MarkOfTheWild()
	IWin:Thorns()
	IWin:BerserkFear()
	IWin:CancelRoot()
	IWin:CancelSnare()
	IWin:BearForm()
	IWin:FeralCharge()
	IWin:FaerieFireFeralRanged()
	IWin:UseItemConsumableAOEOffensiveNoGCD()
	IWin:UseItemConsumableAOEOffensiveGCD()
	IWin:FaerieFireFeral()
	IWin:DemoralizingRoar()
	IWin:SetReservedRage("Demoralizing Roar", "buff", "target")
	IWin:Enrage()
	IWin:UseItemConsumableOffensiveNoGCD(true)
	IWin:UseItemTrinketOffensiveNoGCD(true)
	IWin:CastCDShortOffensiveNoGCD(true)
	IWin:Swipe()
	IWin:SetReservedRageSwipe()
	IWin:FaerieFireFeral(true)
	IWin:Maul()
	IWin:SetReservedRage("Maul", "nocooldown")
	IWin:SavageBite(IWin_Settings["GCD"])
	IWin:SetReservedRageSavageBite()
	IWin:FaerieFireFeralRefresh()
	IWin:Swipe(true)
	IWin:Powershift()
	IWin:StartAttack()
end

SLASH_ITANKFOCUSDRUID1 = "/itankfocus"
function SlashCmdList.ITANKFOCUSDRUID()
	IWin:InitializeRotation()
	IWin:CancelSalvation()
	IWin:TargetEnemy()
	IWin:MarkSkull()
	IWin:UseItemTrinketOffensivePrepull(true)
	IWin:MarkOfTheWild()
	IWin:Thorns()
	IWin:BerserkFear()
	IWin:CancelRoot()
	IWin:CancelSnare()
	IWin:BearForm()
	IWin:FeralCharge()
	IWin:FaerieFireFeralRanged()
	IWin:FaerieFireFeral(true)
	IWin:DemoralizingRoar()
	IWin:SetReservedRage("Demoralizing Roar", "buff", "target")
	IWin:Enrage()
	IWin:UseItemConsumableOffensiveNoGCD(true)
	IWin:UseItemTrinketOffensiveNoGCD(true)
	IWin:CastCDShortOffensiveNoGCD(true)
	IWin:Maul()
	IWin:SetReservedRage("Maul", "nocooldown")
	IWin:SavageBite(IWin_Settings["GCD"], true)
	IWin:SetReservedRageSavageBite(true)
	IWin:FaerieFireFeralRefresh()
	IWin:Swipe(true)
	IWin:Powershift()
	IWin:StartAttack()
end

SLASH_ICHASEDRUID1 = "/ichase"
function SlashCmdList.ICHASEDRUID()
	IWin:TargetEnemy()
	IWin:InitializeRotation()
	IWin:CancelRootReact()
	IWin:CancelSnare()
	IWin:TravelForm()
	IWin:StartAttack()
end

SLASH_IRUNDRUID1 = "/irun"
function SlashCmdList.IRUNDRUID()
	IWin:TargetEnemy()
	IWin:InitializeRotation()
	--IWin:NaturesGrasp() --outdoors test missing
	IWin:CancelRootReact()
	IWin:CancelSnareReact()
	IWin:TravelForm()
	IWin:StartAttack()
end

SLASH_ITAUNTDRUID1 = "/itaunt"
function SlashCmdList.ITAUNTDRUID()
	IWin:TargetEnemy()
	IWin:InitializeRotation()
	IWin:BearForm()
	IWin:Growl()
	IWin:StartAttack()
end