if UnitClass("player") ~= "Warrior" then return end

SLASH_IDPSWARRIOR1 = "/idps"
function SlashCmdList.IDPSWARRIOR()
	IWin:InitializeRotation()
	IWin:TargetEnemy()
	IWin:OverpowerReact()
	IWin:UseItemTrinketOffensivePrepull(true)
	IWin:BattleShoutRefreshOOC()
	IWin:ChargePartySize()
	IWin:InterceptPartySize()
	IWin:DPSStance()
	IWin:UseItemConsumableOffensiveNoGCD()
	IWin:UseItemTrinketOffensiveNoGCD()
	IWin:CastCDShortOffensiveNoGCD()
	IWin:UseItemConsumableDefensive("Elixir of Poison Resistance", "Naxxramas")
	IWin:BattleShout()
	IWin:SetReservedRage("Battle Shout", "buff", "player")
	IWin:SunderArmorDPSRefresh(4)
	IWin:SweepingStrikes()
	IWin:SetReservedRageSweepingStrikes()
	IWin:Whirlwind(IWin_Settings["GCD"])
	IWin:SetReservedRageWhirlwind()
	IWin:UseItemConsumableAOEOffensiveNoGCD()
	IWin:UseItemConsumableAOEOffensiveGCD()
	IWin:SunderArmorElite()
	IWin:BloodthirstHighAP(IWin_Settings["GCD"])
	IWin:SetReservedRageBloodthirstHighAP()
	IWin:Execute(IWin_Settings["GCD"])
	IWin:SetReservedRageExecute()
	IWin:HamstringJousting()
	IWin:Slam()
	IWin:SetReservedRageSlam()
	--IWin:SetSlamQueued()
	IWin:Execute2Hander()
	IWin:SunderArmorDPS2Hander()
	IWin:SetReservedRageSunderArmorDPS2Hander()
	IWin:ShieldSlam(IWin_Settings["GCD"])
	IWin:SetReservedRage("Shield Slam", "cooldown")
	IWin:MortalStrike(IWin_Settings["GCD"])
	IWin:SetReservedRage("Mortal Strike", "cooldown")
	IWin:Bloodthirst(IWin_Settings["GCD"])
	IWin:SetReservedRageBloodthirst()
	IWin:UseItemTrinketOffensiveGCD()
	IWin:CastCDShortOffensiveGCD()
	IWin:CastCDLongOffensiveGCD()
	IWin:Whirlwind(IWin_Settings["GCD"], true)
	IWin:SetReservedRageWhirlwindNotEnemyInRange()
	IWin:Overpower()
	IWin:MasterStrike()
	IWin:SetReservedRageMasterStrike()
	IWin:ConcussionBlow()
	IWin:ThunderClapDPS()
	IWin:BattleShoutRefresh(true)
	IWin:DemoralizingShout(true)
	IWin:SetReservedRageDemoralizingShout(true)
	IWin:Rend()
	IWin:SunderArmorDPSRefresh(7)
	IWin:SunderArmorDPS()
	IWin:SetReservedRageSunderArmorDPS()
	IWin:BerserkerRage()
	IWin:HeroicStrike()
	IWin:SetReservedRageHeroicStrike()
	IWin:Cleave()
	IWin:SetReservedRageCleave()
	IWin:MasterStrikeWindfury()
	IWin:SetReservedRageMasterStrikeWindfury()
	IWin:PummelWindfury()
	IWin:SetReservedRagePummelWindfury()
	IWin:HamstringWindfury()
	IWin:SetReservedRageHamstringWindfury()
	IWin:SunderArmorWindfury()
	IWin:SetReservedRageSunderArmorWindfury()
	IWin:StartAttack()
end

SLASH_IDPSFOCUSWARRIOR1 = "/idpsfocus"
function SlashCmdList.IDPSFOCUSWARRIOR()
	IWin:InitializeRotation()
	IWin:TargetEnemy()
	IWin:OverpowerReact()
	IWin:UseItemTrinketOffensivePrepull(true)
	IWin:BattleShoutRefreshOOC()
	IWin:ChargePartySize()
	IWin:InterceptPartySize()
	IWin:DPSStance(true)
	IWin:UseItemConsumableOffensiveNoGCD()
	IWin:UseItemTrinketOffensiveNoGCD()
	IWin:CastCDShortOffensiveNoGCD()
	IWin:UseItemConsumableDefensive("Elixir of Poison Resistance", "Naxxramas")
	IWin:BattleShout()
	IWin:SetReservedRage("Battle Shout", "buff", "player")
	IWin:SunderArmorDPSRefresh(4)
	IWin:SunderArmorElite()
	IWin:BloodthirstHighAP(IWin_Settings["GCD"])
	IWin:SetReservedRageBloodthirstHighAP()
	IWin:Execute(IWin_Settings["GCD"], true)
	IWin:SetReservedRageExecute(true)
	IWin:HamstringJousting(true)
	IWin:Slam()
	IWin:SetReservedRageSlam()
	--IWin:SetSlamQueued()
	IWin:Execute2Hander(true)
	IWin:SunderArmorDPS2Hander()
	IWin:SetReservedRageSunderArmorDPS2Hander()
	IWin:ShieldSlam(IWin_Settings["GCD"])
	IWin:SetReservedRage("Shield Slam", "cooldown")
	IWin:MortalStrike(IWin_Settings["GCD"])
	IWin:SetReservedRage("Mortal Strike", "cooldown")
	IWin:Bloodthirst(IWin_Settings["GCD"])
	IWin:SetReservedRageBloodthirst()
	IWin:UseItemTrinketOffensiveGCD()
	IWin:CastCDShortOffensiveGCD()
	IWin:CastCDLongOffensiveGCD()
	IWin:Whirlwind(IWin_Settings["GCD"], true)
	IWin:SetReservedRageWhirlwindNotEnemyInRange(true)
	IWin:Overpower()
	IWin:MasterStrike()
	IWin:SetReservedRageMasterStrike()
	IWin:ConcussionBlow()
	IWin:BattleShoutRefresh(true)
	IWin:DemoralizingShout(true)
	IWin:SetReservedRageDemoralizingShout(true)
	IWin:Rend()
	IWin:SunderArmorDPSRefresh(7)
	IWin:SunderArmorDPS()
	IWin:SetReservedRageSunderArmorDPS()
	IWin:BerserkerRage()
	IWin:HeroicStrike(true)
	IWin:SetReservedRageHeroicStrike(true)
	IWin:MasterStrikeWindfury()
	IWin:SetReservedRageMasterStrikeWindfury()
	IWin:PummelWindfury()
	IWin:SetReservedRagePummelWindfury()
	IWin:HamstringWindfury()
	IWin:SetReservedRageHamstringWindfury()
	IWin:SunderArmorWindfury()
	IWin:SetReservedRageSunderArmorWindfury()
	IWin:StartAttack()
end


SLASH_ITANKWARRIOR1 = "/itank"
SLASH_ITANKWARRIOR2 = "/ihodor"
function SlashCmdList.ITANKWARRIOR()
	IWin:InitializeRotation()
	IWin:CancelSalvation()
	IWin:TargetEnemy()
	IWin:OverpowerReact()
	IWin:RevengeReact()
	IWin:UseItemTrinketOffensivePrepull(true)
	IWin:BattleShoutRefreshOOC()
	IWin:ChargePartySize()
	IWin:IntervenePartySize()
	IWin:InterceptPartySize()
	IWin:TankStance()
	IWin:ShieldBlock()
	IWin:ShieldBlockFRD()
	IWin:UseItemConsumableOffensiveNoGCD(true)
	IWin:UseItemTrinketOffensiveNoGCD(true)
	IWin:CastCDShortOffensiveNoGCD(true)
	IWin:UseItemConsumableAOEOffensiveNoGCD()
	IWin:UseItemConsumableAOEOffensiveGCD()
	IWin:ThunderClap(IWin_Settings["GCD"])
	IWin:SetReservedRageThunderClap()
	IWin:WhirlwindDefensiveTactics(IWin_Settings["GCD"])
	IWin:SetReservedRageWhirlwindDefensiveTactics()
	IWin:DemoralizingShout()
	IWin:SetReservedRageDemoralizingShout()
	IWin:BattleShoutRefresh()
	IWin:SetReservedRageBattleShoutRefresh()
	IWin:ConcussionBlowThreat()
	IWin:SlamThreat()
	IWin:SetReservedRageSlamThreat()
	--IWin:SetSlamQueuedThreat()
	IWin:ExecuteDefensiveTactics()
	IWin:SetReservedRageExecuteDefensiveTactics()
	IWin:ShieldSlam(IWin_Settings["GCD"])
	IWin:SetReservedRage("Shield Slam", "cooldown")
	IWin:MortalStrike(IWin_Settings["GCD"])
	IWin:SetReservedRage("Mortal Strike", "cooldown")
	IWin:Bloodthirst(IWin_Settings["GCD"])
	IWin:SetReservedRage("Bloodthirst", "cooldown")
	IWin:BattleShoutRefresh(true)
	IWin:SetReservedRageBattleShoutRefresh(true)
	IWin:OverpowerDefensiveTactics()
	IWin:Revenge()
	IWin:SetReservedRageRevenge()
	IWin:WhirlwindDefensiveTactics(nil, true)
	IWin:SetReservedRageWhirlwindDefensiveTacticsNotEnemyInRange()
	IWin:ConcussionBlow()
	IWin:UseItemTrinketOffensiveGCD(true)
	IWin:CastCDShortOffensiveGCD(true)
	IWin:SunderArmorFirstStack()
	IWin:DemoralizingShout(true)
	IWin:SetReservedRageDemoralizingShout(true)
	IWin:SunderArmor()
	IWin:SetReservedRage("Sunder Armor", "nocooldown")
	IWin:BerserkerRage()
	IWin:HeroicStrike()
	IWin:SetReservedRageHeroicStrike()
	IWin:Cleave()
	IWin:SetReservedRageCleave()
	IWin:StartAttack()
end

SLASH_ITANKFOCUSWARRIOR1 = "/itankfocus"
function SlashCmdList.ITANKFOCUSWARRIOR()
	IWin:InitializeRotation()
	IWin:CancelSalvation()
	IWin:TargetEnemy()
	IWin:OverpowerReact()
	IWin:RevengeReact()
	IWin:UseItemTrinketOffensivePrepull(true)
	IWin:BattleShoutRefreshOOC()
	IWin:ChargePartySize()
	IWin:IntervenePartySize()
	IWin:InterceptPartySize()
	IWin:TankStance()
	IWin:ShieldBlock()
	IWin:UseItemConsumableOffensiveNoGCD(true)
	IWin:UseItemTrinketOffensiveNoGCD(true)
	IWin:CastCDShortOffensiveNoGCD(true)
	IWin:ConcussionBlowThreat()
	IWin:SlamThreat()
	IWin:SetReservedRageSlamThreat()
	--IWin:SetSlamQueuedThreat()
	IWin:ExecuteDefensiveTactics()
	IWin:SetReservedRageExecuteDefensiveTactics()
	IWin:ShieldSlam(IWin_Settings["GCD"])
	IWin:SetReservedRage("Shield Slam", "cooldown")
	IWin:MortalStrike(IWin_Settings["GCD"])
	IWin:SetReservedRage("Mortal Strike", "cooldown")
	IWin:Bloodthirst(IWin_Settings["GCD"])
	IWin:SetReservedRage("Bloodthirst", "cooldown")
	IWin:BattleShoutRefresh(true)
	IWin:SetReservedRageBattleShoutRefresh(true)
	IWin:OverpowerDefensiveTactics()
	IWin:Revenge()
	IWin:SetReservedRageRevenge()
	IWin:WhirlwindDefensiveTactics(nil, true)
	IWin:SetReservedRageWhirlwindDefensiveTacticsNotEnemyInRange(true)
	IWin:ConcussionBlow()
	IWin:UseItemTrinketOffensiveGCD(true)
	IWin:CastCDShortOffensiveGCD(true)
	IWin:SunderArmorFirstStack()
	IWin:DemoralizingShout(true)
	IWin:SetReservedRageDemoralizingShout(true)
	IWin:SunderArmor()
	IWin:SetReservedRage("Sunder Armor", "nocooldown")
	IWin:BerserkerRage()
	IWin:HeroicStrike(true)
	IWin:SetReservedRageHeroicStrike(true)
	IWin:StartAttack()
end

SLASH_ICHASEWARRIOR1 = "/ichase"
function SlashCmdList.ICHASEWARRIOR()
	IWin:InitializeRotation()
	IWin:TargetEnemy()
	IWin:Charge()
	IWin:Intercept()
	IWin:Intervene()
	IWin:Hamstring()
	IWin:PiercingHowl()
	IWin:StartAttack()
end

SLASH_IKICKWARRIOR1 = "/ikick"
function SlashCmdList.IKICKWARRIOR()
	IWin:InitializeRotation()
	IWin:TargetEnemy()
	IWin:ShieldBash()
	IWin:Pummel()
	IWin:StartAttack()
end

SLASH_IFEARDANCEWARRIOR1 = "/ifeardance"
function SlashCmdList.IFEARDANCEWARRIOR()
	IWin:InitializeRotation()
	IWin:TargetEnemy()
	IWin:BerserkerRageImmune()
	IWin:StartAttack()
end

SLASH_ITAUNTWARRIOR1 = "/itaunt"
function SlashCmdList.ITAUNTWARRIOR()
	IWin:InitializeRotation()
	IWin:TargetEnemy()
	IWin:Taunt()
	IWin:MockingBlow()
	IWin:StartAttack()
end

SLASH_ISHOOTWARRIOR1 = "/ishoot"
function SlashCmdList.ISHOOTWARRIOR()
	IWin:InitializeRotation()
	IWin:TargetEnemy()
	IWin:RangedAttackAny()
	IWin:MarkSkull()
end