if UnitClass("player") ~= "Rogue" then return end

SLASH_IDPSROGUE1 = "/idps"
function SlashCmdList.IDPSROGUE()
	IWin:InitializeRotation()
	IWin:TargetEnemy()
	IWin:PickPocket()
	IWin:Ambush()
	IWin:Garrote()
	IWin:CheapShot()
	IWin:UseItemTrinketOffensivePrepull(true)
	IWin:UseItemConsumableOffensiveNoGCD()
	IWin:UseItemTrinketOffensiveNoGCD()
	IWin:CastCDShortOffensiveNoGCD()
	IWin:CastCDShortOffensiveGCD()
	IWin:UseItemConsumableAOEOffensiveNoGCD()
	IWin:UseItemConsumableAOEOffensiveGCD()
	IWin:Envenom()
	IWin:SetReservedEnergyEnvenom()
	IWin:SliceAndDice()
	IWin:SetReservedEnergySliceAndDice()
	IWin:ExposeArmor()
	IWin:SetReservedEnergyExposeArmor()
	IWin:ShadowOfDeath()
	IWin:SetReservedEnergyShadowOfDeath()
	IWin:Rupture()
	IWin:SetReservedEnergyRupture()
	IWin:Eviscerate()
	IWin:SetReservedEnergyEviscerate()
	IWin:Riposte()
	IWin:BladeFlurry()
	IWin:Gouge()
	IWin:SetReservedEnergyGouge()
	IWin:SurpriseAttack()
	IWin:SetReservedEnergy("Surprise Attack", "cooldown")
	IWin:NoxiousAssault()
	IWin:SetReservedEnergy("Noxious Assault", "nocooldown")
	IWin:Hemorrhage()
	IWin:SetReservedEnergy("Hemorrhage", "nocooldown")
	IWin:Backstab()
	IWin:SetReservedEnergyBackstab()
	IWin:SinisterStrike()
	IWin:StartAttack()
end

SLASH_IDPSFOCUSROGUE1 = "/idpsfocus"
function SlashCmdList.IDPSFOCUSROGUE()
	IWin:InitializeRotation()
	IWin:TargetEnemy()
	IWin:PickPocket()
	IWin:Ambush()
	IWin:Garrote()
	IWin:CheapShot()
	IWin:UseItemTrinketOffensivePrepull(true)
	IWin:UseItemConsumableOffensiveNoGCD()
	IWin:UseItemTrinketOffensiveNoGCD()
	IWin:CastCDShortOffensiveNoGCD()
	IWin:CastCDShortOffensiveGCD()
	IWin:Envenom()
	IWin:SetReservedEnergyEnvenom()
	IWin:SliceAndDice()
	IWin:SetReservedEnergySliceAndDice()
	IWin:ExposeArmor()
	IWin:SetReservedEnergyExposeArmor()
	IWin:ShadowOfDeath()
	IWin:SetReservedEnergyShadowOfDeath()
	IWin:Rupture()
	IWin:SetReservedEnergyRupture()
	IWin:Eviscerate()
	IWin:SetReservedEnergyEviscerate()
	IWin:Riposte()
	IWin:BladeFlurry(true)
	IWin:Gouge()
	IWin:SetReservedEnergyGouge()
	IWin:SurpriseAttack()
	IWin:SetReservedEnergy("Surprise Attack", "cooldown")
	IWin:NoxiousAssault()
	IWin:SetReservedEnergy("Noxious Assault", "nocooldown")
	IWin:Hemorrhage()
	IWin:SetReservedEnergy("Hemorrhage", "nocooldown")
	IWin:Backstab()
	IWin:SetReservedEnergyBackstab()
	IWin:SinisterStrike()
	IWin:StartAttack()
end

SLASH_IKICKROGUE1 = "/ikick"
function SlashCmdList.IKICKROGUE()
	IWin:InitializeRotation()
	IWin:TargetEnemy()
	IWin:Kick()
	IWin:DeadlyThrow()
	IWin:StartAttack()
end
