if UnitClass("player") ~= "Paladin" then return end

SLASH_IDPSPALADIN1 = "/idps"
function SlashCmdList.IDPSPALADIN()
	IWin:InitializeRotation()
	IWin:CancelPlayerBuff("Righteous Fury")
	IWin:TargetEnemy()
	IWin:MarkSkull()
	IWin:UseItemTrinketOffensivePrepull(true)
	IWin:Aura()
	IWin:Blessing()
	IWin:SealOfWisdom(10)
	IWin:SealOfWisdomElite()
	IWin:SealOfLightElite()
	IWin:SealOfTheCrusaderElite()
	IWin:SealOfJusticeElite()
	IWin:SealOfCommand(10)
	IWin:SealOfRighteousness(10)
	IWin:UseItemConsumableOffensiveNoGCD()
	IWin:UseItemTrinketOffensiveNoGCD()
	IWin:CastCDShortOffensiveNoGCD()
	IWin:JudgementReact()
	IWin:JudgementRanged(30,IWin_Settings["GCD"])
	IWin:ExorcismRanged(30)
	IWin:HammerOfWrathRanged(30)
	IWin:Consecration(25)
	IWin:HolyWrath(25)
	IWin:UseItemConsumableAOEOffensiveNoGCD()
	IWin:UseItemConsumableAOEOffensiveGCD()
	IWin:CrusaderStrikeZeal(10,IWin_Settings["GCD"])
	IWin:HolyStrikeHolyMight(IWin_Settings["GCD"])
	IWin:CrusaderStrike(15,IWin_Settings["GCD"])
	IWin:HolyStrike(IWin_Settings["GCD"])
	IWin:Judgement(30,IWin_Settings["GCD"])
	IWin:Exorcism(30)
	IWin:HammerOfWrath(30)
	IWin:RepentanceRaid()
	IWin:ConsecrationFocus(90)
	IWin:CastCDShortOffensiveGCD()
	IWin:StartAttack()
end

SLASH_IDPSFOCUSPALADIN1 = "/idpsfocus"
function SlashCmdList.IDPSFOCUSPALADIN()
	IWin:InitializeRotation()
	IWin:CancelPlayerBuff("Righteous Fury")
	IWin:TargetEnemy()
	IWin:MarkSkull()
	IWin:UseItemTrinketOffensivePrepull(true)
	IWin:Aura()
	IWin:Blessing()
	IWin:SealOfWisdom(10)
	IWin:SealOfWisdomElite()
	IWin:SealOfLightElite()
	IWin:SealOfTheCrusaderElite()
	IWin:SealOfJusticeElite()
	IWin:SealOfCommand(10)
	IWin:SealOfRighteousness(10)
	IWin:UseItemConsumableOffensiveNoGCD()
	IWin:UseItemTrinketOffensiveNoGCD()
	IWin:CastCDShortOffensiveNoGCD()
	IWin:JudgementReact()
	IWin:JudgementRanged(30,IWin_Settings["GCD"])
	IWin:ExorcismRanged(30)
	IWin:HammerOfWrathRanged(30)
	IWin:CrusaderStrikeZeal(10,IWin_Settings["GCD"])
	IWin:HolyStrikeHolyMight(IWin_Settings["GCD"])
	IWin:CrusaderStrike(15,IWin_Settings["GCD"])
	IWin:HolyStrike(IWin_Settings["GCD"])
	IWin:Judgement(30,IWin_Settings["GCD"])
	IWin:Exorcism(30)
	IWin:HammerOfWrath(30)
	IWin:RepentanceRaid()
	IWin:ConsecrationFocus(90)
	IWin:CastCDShortOffensiveGCD()
	IWin:StartAttack()
end

SLASH_ITANKPALADIN1 = "/itank"
function SlashCmdList.ITANKPALADIN()
	IWin:InitializeRotation()
	IWin:CancelSalvation()
	IWin:TargetEnemy()
	IWin:MarkSkull()
	IWin:UseItemTrinketOffensivePrepull(true)
	IWin:RighteousFury()
	IWin:Aura()
	IWin:Blessing()
	IWin:UseItemConsumableOffensiveNoGCD(true)
	IWin:UseItemTrinketOffensiveNoGCD(true)
	IWin:CastCDShortOffensiveNoGCD(true)
	IWin:Consecration(25)
	IWin:UseItemConsumableAOEOffensiveNoGCD()
	IWin:UseItemConsumableAOEOffensiveGCD()
	IWin:HolyShockPull(20)
	IWin:HolyShield(15, 1)
	IWin:HolyShield(15, 3, true)
	IWin:HolyShock(15, 50)
	IWin:SealOfWisdom(10)
	IWin:SealOfWisdomElite()
	IWin:SealOfLightElite()
	IWin:SealOfTheCrusaderElite()
	IWin:SealOfJusticeElite()
	IWin:SealOfWisdomEco()
	IWin:SealOfCommand(15)
	IWin:SealOfRighteousness(15)
	IWin:ExorcismRanged(30)
	IWin:JudgementRanged(30,IWin_Settings["GCD"])
	IWin:HolyStrike(IWin_Settings["GCD"])
	IWin:Exorcism(30)
	IWin:Judgement(30,IWin_Settings["GCD"])
	IWin:HolyShock(15, 80)
	IWin:ConsecrationFocus(70)
	IWin:RepentanceRaid()
	IWin:CastCDShortOffensiveGCD(true)
	IWin:StartAttack()
end

SLASH_ITANKFOCUSPALADIN1 = "/itankfocus"
function SlashCmdList.ITANKFOCUSPALADIN()
	IWin:InitializeRotation()
	IWin:CancelSalvation()
	IWin:TargetEnemy()
	IWin:MarkSkull()
	IWin:UseItemTrinketOffensivePrepull(true)
	IWin:RighteousFury()
	IWin:Aura()
	IWin:Blessing()
	IWin:UseItemConsumableOffensiveNoGCD(true)
	IWin:UseItemTrinketOffensiveNoGCD(true)
	IWin:CastCDShortOffensiveNoGCD(true)
	IWin:HolyShockPull(20)
	IWin:HolyShield(15, 3, true)
	IWin:HolyShock(15, 50)
	IWin:SealOfWisdom(10)
	IWin:SealOfWisdomElite()
	IWin:SealOfLightElite()
	IWin:SealOfTheCrusaderElite()
	IWin:SealOfJusticeElite()
	IWin:SealOfCommand(15, true)
	IWin:SealOfRighteousness(15, true)
	IWin:ExorcismRanged(30)
	IWin:JudgementRanged(30,IWin_Settings["GCD"])
	IWin:HolyStrike(IWin_Settings["GCD"])
	IWin:Exorcism(30)
	IWin:Judgement(30,IWin_Settings["GCD"])
	IWin:HolyShock(15, 80)
	IWin:ConsecrationFocus(70)
	IWin:RepentanceRaid()
	IWin:CastCDShortOffensiveGCD(true)
	IWin:StartAttack()
end

SLASH_IECOPALADIN1 = "/ieco"
function SlashCmdList.IECOPALADIN()
	IWin:InitializeRotation()
	IWin:TargetEnemy()
	IWin:Aura()
	IWin:Blessing()
	IWin:SealOfWisdom(10)
	IWin:SealOfWisdomElite()
	IWin:SealOfLightElite()
	IWin:SealOfTheCrusaderElite()
	IWin:SealOfJusticeElite()
	IWin:SealOfWisdomEco()
	IWin:JudgementRanged(30,IWin_Settings["GCD"])
	IWin:HolyShield(5, 3)
	IWin:HolyStrike(IWin_Settings["GCD"])
	IWin:Judgement(30,IWin_Settings["GCD"])
	IWin:HolyShock(15)
	IWin:StartAttack()
end

SLASH_IJUDGEPALADIN1 = "/ijudge"
function SlashCmdList.IJUDGEPALADIN()
	IWin:InitializeRotation()
	IWin:TargetEnemy()
	IWin:SealOfWisdomElite()
	IWin:SealOfLightElite()
	IWin:SealOfTheCrusaderElite()
	IWin:SealOfJusticeElite()
	IWin:SealOfCommand(15)
	IWin:SealOfRighteousness(15)
	IWin:Judgement(30,IWin_Settings["GCD"])
	IWin:StartAttack()
end

-- TODO: not working
SLASH_ICHASEPALADIN1 = "/ichase"
function SlashCmdList.ICHASEPALADIN()
	IWin:InitializeRotation()
	IWin:TargetEnemy()
	IWin:HandOfFreedom()
	IWin:SealOfJustice()
	IWin:JudgementReact()
	IWin:Cleanse()
	IWin:Purify()
	IWin:StartAttack()
end

SLASH_ISTUNPALADIN1 = "/istun"
function SlashCmdList.ISTUNPALADIN()
	IWin:InitializeRotation()
	IWin:TargetEnemy()
	IWin:HammerOfJustice()
	IWin:StartAttack()
	IWin:Repentance()
end

SLASH_ITAUNTPALADIN1 = "/itaunt"
function SlashCmdList.ITAUNTPALADIN()
	IWin:InitializeRotation()
	IWin:TargetEnemy()
	IWin:HandOfReckoning()
	IWin:StartAttack()
end

SLASH_IBUBBLEHEARTHPALADIN1 = "/ibubblehearth"
function SlashCmdList.IBUBBLEHEARTHPALADIN()
	IWin:InitializeRotation()
	IWin:DivineShield()
	IWin:UseItem("Hearthstone")
end